'use strict';

/*
 * build-sample.js — produces the labelled SAMPLE dataset the dashboard ships
 * with, using the SAME normalize + rank code as production. It creates two
 * snapshots (last week, this week) so the growth/trend tiles have real data.
 * Everything it writes is badged source:"sample".
 *
 * This is demo tooling, not the production run. Production is src/ingest.js.
 */

const fs = require('fs');
const path = require('path');
const { normalizeRecord } = require('../src/normalize');
const { buildLeaderboards, growth } = require('../src/rank');
const { MockProvider } = require('../src/provider');

const PRIVATE = ['sukhpreet.kaur'];
const provider = new MockProvider({ privateHandles: PRIVATE });
const platforms = ['instagram', 'tiktok', 'facebook'];
const registry = JSON.parse(fs.readFileSync(path.join(__dirname, 'sample-registry.json'), 'utf8'));

// per-person growth factor so last week's followers are a bit lower than now
function growthFactor(name) {
  let h = 0; for (const c of name) h = (h * 31 + c.charCodeAt(0)) >>> 0;
  return 0.90 + (h % 80) / 1000; // 0.90 .. 0.98
}

async function snapshot(scale, capturedAt) {
  const records = [];
  const states = { private: [], unresolved: [], unconfirmed: [], excludedBackOffice: [] };
  for (const e of registry.employees) {
    if (e.dashboardRelevant === false) { states.excludedBackOffice.push({ name: e.name, role: e.role }); continue; }
    for (const pf of platforms) {
      const handle = e.handles ? e.handles[pf] : null;
      const entry = { name: e.name, role: e.role, platform: pf, handle };
      if (!handle || e.confirmed !== true) {
        records.push(normalizeRecord(entry, null, capturedAt));
        if (handle && e.confirmed !== true) states.unconfirmed.push({ name: e.name, platform: pf, handle });
        continue;
      }
      let raw = await provider.fetchProfile(pf, handle);
      if (raw && !raw.notFound && !raw.isPrivate && scale !== 1) {
        const f = scale * growthFactor(e.name);
        raw = Object.assign({}, raw, { followers: Math.round(raw.followers * f) });
      }
      const rec = normalizeRecord(entry, raw, capturedAt);
      records.push(rec);
      if (!rec.resolved) states.unresolved.push({ name: e.name, platform: pf, handle });
      else if (rec.isPrivate) states.private.push({ name: e.name, platform: pf, handle });
    }
  }
  return { records, states };
}

(async () => {
  const lastWeek = new Date(Date.now() - 7 * 864e5).toISOString();
  const nowIso = new Date().toISOString();

  const prev = await snapshot(0.94, lastWeek);   // one factor short of "now"
  const curr = await snapshot(1.0, nowIso);

  const leaderboards = buildLeaderboards(curr.records, platforms);
  const trend = growth(prev.records, curr.records);

  const meta = {
    company: registry.company, orn: registry.orn,
    capturedAt: nowIso, source: 'sample', provider: 'mock', platforms,
    relevantCount: registry.employees.filter(e => e.dashboardRelevant !== false).length,
    resolvedProfiles: curr.records.filter(r => r.resolved && !r.isPrivate).length,
    note: 'SAMPLE data \u2014 generated by the real pipeline with deterministic fake numbers. Not live. Add confirmed handles + APIFY_TOKEN to go live.',
    trendAvailable: trend.length > 0,
  };

  const outDir = path.join(__dirname, '..', 'data');
  fs.mkdirSync(path.join(outDir, 'history'), { recursive: true });
  fs.writeFileSync(path.join(outDir, 'latest.json'), JSON.stringify({ meta, records: curr.records, leaderboards, states: curr.states, trend }, null, 2));
  fs.writeFileSync(path.join(outDir, 'history', `${lastWeek.slice(0, 10)}.json`), JSON.stringify({ meta: Object.assign({}, meta, { capturedAt: lastWeek }), records: prev.records }, null, 2));
  fs.writeFileSync(path.join(outDir, 'history', `${nowIso.slice(0, 10)}.json`), JSON.stringify({ meta, records: curr.records }, null, 2));
  console.log(`[sample] ${meta.resolvedProfiles} profiles, trend rows=${trend.length}, top composite=${leaderboards.combined.composite[0] && leaderboards.combined.composite[0].name}`);
})();
